# Generated by Django 6.0.8 on 2026-09-30 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueioLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(max_length=32, unique=True)),
                ('falhas', models.PositiveIntegerField(default=0)),
                ('nivel', models.PositiveIntegerField(default=0)),
                ('bloqueado_ate', models.DateTimeField(blank=True, null=True)),
                ('permanente', models.BooleanField(default=False)),
                ('reserva_ate', models.DateTimeField(blank=True, null=True)),
                ('reserva_token', models.CharField(blank=True, max_length=32)),
            ],
        ),
    ]
