# Generated by Django 6.0.8 on 2026-09-21 06:50

import django.db.models.deletion
import nucleo.upload_paths
import nucleo.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nucleo', '0001_initial'),
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaArtigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Psicologia Clínica, Relacionamentos, Neuropsicologia.', max_length=100, verbose_name='Nome da Categoria')),
                ('slug', models.SlugField(blank=True, help_text='Identificador único da categoria na URL.', max_length=120, unique=True, verbose_name='Slug da URL')),
                ('descricao', models.TextField(blank=True, help_text='Breve contextualização editorial sobre os temas desta categoria.', verbose_name='Descrição da Categoria')),
                ('ordem', models.PositiveIntegerField(default=1, verbose_name='Ordem de Exibição')),
                ('ativo', models.BooleanField(default=True, help_text='Categorias inativas não aparecem nos filtros públicos.', verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Categoria de Artigo',
                'verbose_name_plural': 'Categorias de Artigos',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título claro e informativo para leitores e buscadores.', max_length=200, verbose_name='Título do Artigo')),
                ('slug', models.SlugField(blank=True, help_text='Identificador único na URL. Gerado automaticamente na criação; evite alterar após publicado.', max_length=220, unique=True, verbose_name='Slug da URL')),
                ('resumo', models.TextField(blank=True, help_text='Resumo conciso exibido nos cards da listagem e da Home.', verbose_name='Resumo / Linha Fina')),
                ('conteudo', models.TextField(blank=True, help_text='Texto do artigo formatado em Markdown seguro. Use ## para subtítulos (H2). Tags script e H1 são bloqueadas.', verbose_name='Conteúdo (Markdown)')),
                ('imagem_capa', models.ImageField(blank=True, help_text='Proporção recomendada: ~16:9. Formatos suportados: JPG, PNG, WEBP.', null=True, upload_to=nucleo.upload_paths.caminho_upload_artigo, validators=[nucleo.validators.validar_imagem], verbose_name='Imagem de Capa')),
                ('texto_alternativo_imagem', models.CharField(blank=True, help_text='Descreva objetivamente a imagem para leitores de tela e acessibilidade.', max_length=200, verbose_name='Texto Alternativo da Capa (alt)')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('publicado', 'Publicado')], default='rascunho', help_text="Apenas artigos 'Publicados' com data <= agora aparecem publicamente no site.", max_length=20, verbose_name='Status Editorial')),
                ('destaque', models.BooleanField(default=False, help_text='Se marcado, será exibido no topo da página de Conteúdos.', verbose_name='Destaque Principal na Listagem')),
                ('data_publicacao', models.DateTimeField(blank=True, help_text="Se o status for 'Publicado' e este campo estiver vazio, será preenchido com a data/hora atual.", null=True, verbose_name='Data de Publicação')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('meta_titulo', models.CharField(blank=True, help_text='Título conciso para buscadores (ideal até ~60-70 caracteres). Deixe vazio para usar o título do artigo.', max_length=70, verbose_name='Meta Title (SEO)')),
                ('meta_descricao', models.TextField(blank=True, help_text='Resumo utilizado por mecanismos de busca (ideal entre 140 e 160 caracteres). Deixe vazio para usar o resumo.', verbose_name='Meta Description (SEO)')),
                ('autor', models.ForeignKey(blank=True, help_text='Profissional responsável pela autoria do texto. Deixe vazio se não houver autoria confirmada.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artigos', to='nucleo.profissional', verbose_name='Autor(a)')),
                ('servico_relacionado', models.ForeignKey(blank=True, help_text='Serviço do Instituto vinculado ao tema do artigo para direcionamento de leitura.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artigos_relacionados', to='servicos.servico', verbose_name='Serviço Relacionado')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artigos', to='conteudos.categoriaartigo', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Artigo',
                'verbose_name_plural': 'Artigos',
                'ordering': ['-data_publicacao', '-data_criacao'],
            },
        ),
    ]
