# Generated by Django 6.0.8 on 2026-09-30 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artigo',
            options={'ordering': ['-data_publicacao', '-data_criacao'], 'permissions': [('gerenciar_blog', 'Pode gerenciar o Blog pelo painel reservado')], 'verbose_name': 'Artigo', 'verbose_name_plural': 'Artigos'},
        ),
        migrations.AddField(
            model_name='artigo',
            name='apagar_em',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Apagar automaticamente em'),
        ),
        migrations.AddField(
            model_name='artigo',
            name='fonte',
            field=models.CharField(choices=[('montserrat', 'Montserrat'), ('georgia', 'Georgia'), ('arial', 'Arial'), ('palatino', 'Palatino')], default='montserrat', max_length=20),
        ),
        migrations.AddField(
            model_name='artigo',
            name='formato_html',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
