# Generated by Django 6.0.8 on 2026-09-30 07:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudos', '0002_alter_artigo_options_artigo_apagar_em_artigo_fonte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='capa_x',
            field=models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='artigo',
            name='capa_y',
            field=models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
