# Generated by Django 6.0.8 on 2026-09-21 03:33

import nucleo.upload_paths
import nucleo.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_instituto', models.CharField(default='Instituto Mente em Foco', max_length=150, verbose_name='Nome do Instituto')),
                ('razao_social', models.CharField(blank=True, max_length=200, verbose_name='Razão Social / Nome Jurídico')),
                ('slogan_principal', models.CharField(default='COMPREENDER • CUIDAR • RECONSTRUIR', max_length=255, verbose_name='Conceito / Slogan Principal')),
                ('frase_institucional', models.TextField(default='Psicologia e Neuropsicologia para compreender a mente, cuidar das emoções e construir novos caminhos.', verbose_name='Frase Institucional')),
                ('frase_emocional', models.CharField(default='Sua história merece ser compreendida.', max_length=255, verbose_name='Frase Emocional')),
                ('cta_principal', models.CharField(default='Comece por você.', max_length=100, verbose_name='CTA Institucional Principal')),
                ('mensagem_whatsapp_padrao', models.TextField(default='Olá, Mari. Conheci o Instituto Mente em Foco pelo site e gostaria de informações sobre o atendimento psicológico/neuropsicológico.', verbose_name='Mensagem Padrão do WhatsApp')),
                ('telefone', models.CharField(blank=True, max_length=30, verbose_name='Telefone Fixo')),
                ('whatsapp', models.CharField(blank=True, help_text='Somente números com código do país e DDD (Ex: 5561999999999)', max_length=30, verbose_name='WhatsApp Comercial')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail de Contato')),
                ('instagram', models.URLField(blank=True, verbose_name='Link do Instagram Oficial')),
                ('endereco_texto', models.CharField(blank=True, max_length=255, verbose_name='Endereço Completo')),
                ('modalidade_atendimento', models.CharField(blank=True, help_text='Ex: Presencial, Online ou Híbrido', max_length=100, verbose_name='Modalidade de Atendimento')),
                ('cidade', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=2, verbose_name='Estado (UF)')),
                ('mapa_url', models.URLField(blank=True, verbose_name='Link do Google Maps')),
                ('horario_atendimento', models.CharField(blank=True, max_length=150, verbose_name='Horário de Atendimento')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=nucleo.upload_paths.caminho_upload_institucional, validators=[nucleo.validators.validar_imagem], verbose_name='Logotipo Principal')),
                ('logo_horizontal', models.ImageField(blank=True, null=True, upload_to=nucleo.upload_paths.caminho_upload_institucional, validators=[nucleo.validators.validar_imagem], verbose_name='Logotipo Horizontal')),
                ('logo_vertical', models.ImageField(blank=True, null=True, upload_to=nucleo.upload_paths.caminho_upload_institucional, validators=[nucleo.validators.validar_imagem], verbose_name='Logotipo Vertical')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to=nucleo.upload_paths.caminho_upload_institucional, validators=[nucleo.validators.validar_imagem], verbose_name='Favicon (Ícone de Navegador)')),
                ('imagem_compartilhamento_padrao', models.ImageField(blank=True, null=True, upload_to=nucleo.upload_paths.caminho_upload_institucional, validators=[nucleo.validators.validar_imagem], verbose_name='Imagem Padrão Open Graph (1200x630)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Configuração do Site',
                'verbose_name_plural': 'Configuração do Site',
            },
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Mari Menezes', max_length=150, verbose_name='Nome Completo')),
                ('nome_exibicao', models.CharField(default='Psicóloga Mari Menezes', max_length=100, verbose_name='Nome de Exibição')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True, verbose_name='Identificador da URL (Slug)')),
                ('titulo_profissional', models.CharField(default='Psicóloga, palestrante e facilitadora de grupos', max_length=200, verbose_name='Título Profissional')),
                ('atuacao_resumida', models.CharField(default='Psicologia e Neuropsicologia', max_length=200, verbose_name='Área de Atuação Principal')),
                ('biografia_curta', models.TextField(default='Minha prática parte da compreensão de que cada pessoa carrega uma história que precisa ser compreendida antes de ser julgada. Meu trabalho busca oferecer um espaço de escuta profissional, acolhimento e construção de estratégias para diferentes momentos da vida.', verbose_name='Biografia Curta / Apresentação')),
                ('biografia_completa', models.TextField(blank=True, help_text='Texto detalhado da trajetória profissional para a página Sobre Mim.', verbose_name='Biografia Completa')),
                ('frase_destaque', models.CharField(default='Meu propósito é ajudar pessoas a compreenderem melhor a própria história e encontrarem recursos para seguir seus caminhos.', max_length=255, verbose_name='Frase de Destaque')),
                ('registro_profissional', models.CharField(blank=True, help_text='Número oficial do CRP com região (Ex: CRP 00/00000). Deixar vazio se pendente.', max_length=50, verbose_name='Registro Profissional (CRP)')),
                ('formacao_resumida', models.TextField(blank=True, help_text='Inserir somente graduações, especializações e títulos acadêmicos reais comprovados.', verbose_name='Formação e Qualificações Reais')),
                ('foto_principal', models.ImageField(blank=True, help_text='Proporção recomendada: vertical ~4:5.', null=True, upload_to=nucleo.upload_paths.caminho_upload_profissional, validators=[nucleo.validators.validar_imagem], verbose_name='Fotografia Principal (Hero)')),
                ('foto_sobre', models.ImageField(blank=True, help_text='Proporção recomendada: vertical ~4:5.', null=True, upload_to=nucleo.upload_paths.caminho_upload_profissional, validators=[nucleo.validators.validar_imagem], verbose_name='Fotografia para Seção Sobre Mim')),
                ('foto_secundaria', models.ImageField(blank=True, null=True, upload_to=nucleo.upload_paths.caminho_upload_profissional, validators=[nucleo.validators.validar_imagem], verbose_name='Fotografia Secundária / Ambiente')),
                ('ordem', models.PositiveIntegerField(default=1, verbose_name='Ordem de Exibição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('destaque', models.BooleanField(default=True, verbose_name='Destaque na Página Inicial')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Profissional',
                'verbose_name_plural': 'Profissionais',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='RedeSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome da Rede')),
                ('url', models.URLField(verbose_name='Link do Perfil')),
                ('icone', models.CharField(choices=[('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('facebook', 'Facebook'), ('whatsapp', 'WhatsApp'), ('outro', 'Outro')], default='instagram', max_length=50, verbose_name='Identificador do Ícone')),
                ('ordem', models.PositiveIntegerField(default=1, verbose_name='Ordem de Exibição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Rede Social',
                'verbose_name_plural': 'Redes Sociais',
                'ordering': ['ordem', 'nome'],
            },
        ),
    ]
