const {chromium}=require('C:/Users/andre/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{
 let password='';for await(const c of process.stdin)password+=c;
 const browser=await chromium.launch({headless:true,channel:'msedge'});
 const page=await browser.newPage({viewport:{width:1440,height:1000}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:8010/area-cliente/entrar/');
 await page.locator('#id_username').fill('Marileides140@email.com');await page.locator('#id_password').fill(password.trim());
 await page.getByRole('button',{name:'Entrar',exact:true}).click();await page.waitForURL('**/area-cliente/');
 await page.goto('http://127.0.0.1:8010/area-cliente/novo/');
 await page.locator('#id_titulo').fill('Teste temporário enquadramento');await page.locator('#editor-visual').fill('Verificação do enquadramento.');
 await page.locator('#id_imagem_capa').setInputFiles('media/profissionais/mari-capa-v3.webp');
 await page.locator('#id_texto_alternativo_imagem').fill('Retrato de Mari.');
 const frame=page.locator('#capa-quadro');await frame.waitFor({state:'visible'});await frame.scrollIntoViewIfNeeded();
 const box=await frame.boundingBox();await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x+box.width/2,box.y+box.height/2+35,{steps:10});await page.mouse.up();
 const pos=await page.locator('#id_capa_y').inputValue();if(pos==='50')throw new Error('Arraste não alterou posição');
 await page.screenshot({path:'scratch/screenshots_reformulacao/blog-enquadramento.png',fullPage:true});
 await page.getByRole('button',{name:'Publicar artigo',exact:true}).click();await page.waitForURL('**/area-cliente/');
 const item=page.locator('.painel-item').filter({hasText:'Teste temporário enquadramento'});await item.getByRole('link',{name:'Editar',exact:true}).click();
 if(await page.locator('#id_capa_y').inputValue()!==pos)throw new Error('Posição não persistiu');
 await page.setViewportSize({width:390,height:844});await frame.scrollIntoViewIfNeeded();await frame.focus();await page.keyboard.press('ArrowDown');
 const adjusted=await page.locator('#id_capa_y').inputValue();if(adjusted===pos)throw new Error('Setas não ajustaram');
 await page.getByRole('button',{name:'Centralizar foto'}).click();if(await page.locator('#id_capa_y').inputValue()!=='50')throw new Error('Reset falhou');
 await frame.focus();await page.keyboard.press('ArrowDown');const finalPos=await page.locator('#id_capa_y').inputValue();
 await page.getByRole('button',{name:'Salvar publicação',exact:true}).click();await page.waitForURL('**/area-cliente/');
 await page.locator('.painel-item').filter({hasText:'Teste temporário enquadramento'}).getByRole('link',{name:'Ver no site'}).click();
 const position=await page.locator('.artigo-capa-wrap img').evaluate(el=>getComputedStyle(el).objectPosition);
 if(position!==`50% ${finalPos}%`)throw new Error('Capa pública incorreta: '+position);
 await page.goto('http://127.0.0.1:8010/area-cliente/');
 await page.locator('.painel-item').filter({hasText:'Teste temporário enquadramento'}).getByRole('link',{name:'Excluir',exact:true}).click();
 await page.getByRole('button',{name:'Excluir artigo',exact:true}).click();
 console.log(JSON.stringify({arraste:pos,persistencia:'ok',teclado:'ok',centralizar:'ok',capaPublica:position,errors}));await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
