# Generated by Django 6.0.8 on 2026-09-21 03:33

import django.db.models.deletion
import nucleo.upload_paths
import nucleo.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaAtuacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Psicologia, Neuropsicologia, Traumas, Separação e Recomeços, Novos Relacionamentos', max_length=150, verbose_name='Nome da Área')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True, verbose_name='Slug da URL')),
                ('titulo', models.CharField(help_text='Título exibido em destaque nos cards e cabeçalhos', max_length=200, verbose_name='Título Editorial')),
                ('resumo', models.TextField(help_text='Texto conciso exibido nos cards da página inicial.', verbose_name='Resumo Curto')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição Completa da Área')),
                ('imagem', models.ImageField(blank=True, help_text='Proporção recomendada: ~4:3.', null=True, upload_to=nucleo.upload_paths.caminho_upload_area, validators=[nucleo.validators.validar_imagem], verbose_name='Fotografia do Card')),
                ('texto_alternativo_imagem', models.CharField(blank=True, help_text='Descreva objetivamente o conteúdo relevante da fotografia para acessibilidade.', max_length=200, verbose_name='Texto Alternativo da Imagem (alt)')),
                ('frase_destaque', models.CharField(blank=True, max_length=255, verbose_name='Frase de Destaque / Citação')),
                ('ordem', models.PositiveIntegerField(default=1, verbose_name='Ordem de Exibição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('mostrar_na_home', models.BooleanField(default=True, verbose_name='Mostrar na Página Inicial')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Área de Atuação',
                'verbose_name_plural': 'Áreas de Atuação',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do Serviço')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True, verbose_name='Slug da URL')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título da Página')),
                ('subtitulo', models.CharField(blank=True, max_length=255, verbose_name='Subtítulo')),
                ('resumo', models.TextField(help_text='Apresentação inicial acolhedora da atuação.', verbose_name='Resumo Explicativo')),
                ('descricao', models.TextField(help_text='Texto explicativo estruturado, sem jargões excessivos e sem promessas de cura.', verbose_name='Descrição Detalhada do Atendimento')),
                ('frase_destaque', models.CharField(blank=True, max_length=255, verbose_name='Frase de Destaque')),
                ('imagem_principal', models.ImageField(blank=True, help_text='Proporção recomendada: ~16:9.', null=True, upload_to=nucleo.upload_paths.caminho_upload_servico, validators=[nucleo.validators.validar_imagem], verbose_name='Imagem Principal da Página')),
                ('texto_alternativo_imagem', models.CharField(blank=True, max_length=200, verbose_name='Texto Alternativo da Imagem (alt)')),
                ('icone', models.CharField(blank=True, help_text='Ex: cerebro, perfil, prancheta, flor', max_length=50, verbose_name='Identificador do Ícone')),
                ('ordem', models.PositiveIntegerField(default=1, verbose_name='Ordem de Exibição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('mostrar_na_home', models.BooleanField(default=True, verbose_name='Mostrar na Página Inicial')),
                ('meta_titulo', models.CharField(blank=True, help_text='Título conciso para buscadores (ideal até ~60-70 caracteres).', max_length=70, verbose_name='Meta Title (SEO)')),
                ('meta_descricao', models.TextField(blank=True, help_text='Resumo utilizado por mecanismos de busca (ideal entre 140 e 160 caracteres).', verbose_name='Meta Description (SEO)')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicos', to='servicos.areaatuacao', verbose_name='Área de Atuação Relacionada')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['ordem', 'nome'],
            },
        ),
    ]
