# Generated by Django 6.0.8 on 2026-09-21 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensagemContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome informado pelo visitante para identificação no contato.', max_length=150, verbose_name='Nome Completo')),
                ('email', models.EmailField(blank=True, help_text='E-mail para resposta. Obrigatório se o telefone não for informado.', max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(blank=True, help_text='Telefone com DDD para contato. Obrigatório se o e-mail não for informado.', max_length=30, verbose_name='Telefone / WhatsApp')),
                ('mensagem', models.TextField(blank=True, help_text='Texto informativo breve sobre o contato (limite de até 2000 caracteres).', max_length=2000, verbose_name='Mensagem Breve')),
                ('aceite_privacidade', models.BooleanField(default=False, help_text='Confirmação de que o visitante leu e concorda com a Política de Privacidade.', verbose_name='Aceite da Política de Privacidade')),
                ('lida', models.BooleanField(default=False, help_text='Controle administrativo interno para identificar mensagens já respondidas ou analisadas.', verbose_name='Mensagem Lida')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Envio')),
                ('servico_interesse', models.ForeignKey(blank=True, help_text='Serviço do Instituto sobre o qual o visitante busca informações (opcional).', limit_choices_to={'ativo': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensagens_contato', to='servicos.servico', verbose_name='Serviço ou Assunto de Interesse')),
            ],
            options={
                'verbose_name': 'Mensagem de Contato',
                'verbose_name_plural': 'Mensagens de Contato',
                'ordering': ['-criado_em'],
            },
        ),
    ]
